using UnityEngine;

namespace UltimateTruckEmpire.World
{
    /// <summary>
    /// Marks an imported Batch 02 mesh as a physical driving surface.
    /// Mesh colliders are generated by the editor import pipeline so the player
    /// truck and traffic use the same physical world as the visual road/bridge.
    /// </summary>
    public sealed class Batch02DriveableSurface : MonoBehaviour
    {
        [SerializeField] private bool collisionEnabled = true;
        public bool CollisionEnabled => collisionEnabled;
    }
}
